spring.application.name=restpick
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.config.import=optional:file:.env[.properties]
google.places.api.key=${key}
google.places.api.url=https://maps.googleapis.com
google.places.api.region=us
google.places.api.language=en