spring.application.name=restpick
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.config.import=optional:file:./.env[.properties]
google.places.api.key=AIzaSyAPbyeJvXCXNsLLAo8X-L4dd9r-RT7_uJQ
google.places.api.url=https://maps.googleapis.com